version: '3'
services:
  client:
    build:
      context: ./client
    volumes:
      - ./client:/src
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - db
      - web
  web:
    container_name: express-api
    build:
      context: ./
    volumes:
      - .:/src
    command: supervisor -e '.' index.js
    ports:
      - "3001:3001"
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    env_file:
      - ./.env
    ports:
      - "3308:3306"
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    env_file:
      - ./.env
    ports:
      - "8081:80"